# Generated by Django 4.1.5 on 2023-01-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('account', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('ifsc', models.BigIntegerField()),
                ('address', models.CharField(max_length=30)),
                ('seller_pic', models.ImageField(upload_to='seller/')),
            ],
            options={
                'db_table': 'seller_table',
            },
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer_table',
        ),
    ]
