# Generated by Django 4.1.5 on 2023-01-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_customer_table_alter_seller_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='user_name',
            field=models.IntegerField(default=0),
        ),
    ]
