# Generated by Django 4.1.5 on 2023-01-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_customer_address_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
